### ISSUE TITLE
Could you please link the platform urls to the questions.

### ISSUE THREAD

**Issue by yaralahruthik** [rr-tri/front-end-hire#1]
Hi Ram

I see that you have been using frontend hire a lot. But I also noticed that you have created this repo that holds the questions. I do not think that it is intentional.

I do not have a problem if you link to each question on the platform to your repo. This helps my platform and let me create more such questions.

I'd appreciate a quick response from you.

Otherwise, I would have to file a copyright issue and take down the repo.

Hope you understand.

**Comment by rr-tri** [comment]
Link and name of question have been added to the each solution's **readme.me** file.

**Comment by yaralahruthik** [comment]
Thanks for understanding! Hope you enjoy the platform!
